### PR TITLE
Add a script to regenerate thumbnails

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
Fix #172.

@cadecairos r?

**Comment by cadecairos** [comment]
Nice! I'll test this out tomorrow morning.

Should we bother with doing it as a transaction?

**Comment by jbuck** [comment]
@cadecairos Nah, not reason to, we can just update as we go. FWIW, I've been testing it with your user account ;) 

```
$ node scripts/regenerate_thumbnails.js "users.id = 249"
Found 4 rows to update
Updated /users/249/projects/6578 thumbnail = {"320":"https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTI0OSZwcm9qZWN0PTY1NzgmcGFnZT0xOTA5OSZ0PTE0NDAwMzMxODgzMjU="}
Updated /users/249/projects/12 thumbnail = {"320":"https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTI0OSZwcm9qZWN0PTEyJnBhZ2U9NzQmdD0xNDQwMDMzMTg4MzI1"}
Updated /users/249/projects/7546 thumbnail = {"320":"https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTI0OSZwcm9qZWN0PTc1NDYmcGFnZT0yMTUxNiZ0PTE0NDAwMzMxODgzMjU="}
Updated /users/249/projects/11904 thumbnail = {"320":"https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTI0OSZwcm9qZWN0PTExOTA0JnBhZ2U9MzIxMDYmdD0xNDQwMDMzMTg4MzI1"}
Thumbnail queue empty. Nice job!
```

**Comment by cadecairos** [comment]
haha nice! 

Are we just gonna wait on server caches to expire vs busting them manually?

**Comment by jbuck** [comment]
How long do the caches exist for? I'm fine either way, but simplicity says we should just wait for them to expire.

**Comment by cadecairos** [comment]
Caches should expire in less than 15 minutes.

R+

**Pull request merged**
