### PR TITLE
Create a webmaker-ratelimit plugin

### LINKED ISSUE #36: Rate Limiting
We should apply rate limits to most API routes to prevent abuse and spam. I'm not sure what kind of rate limiting tools are available for Hapi, but they're sure to be out there.

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #36 

This patch adds a plugin to the server that uses hapi's built in caching for rate limiting.

It's off by default for all routes, and can be configured on a per route basis to limit against any configured parameters.

it can be enabled on a route using `config.plugins`:

```
server.route({
  path: '/foo',
  method: 'post',
  handler: handlerFunc,
  config: {
    auth: {
      mode: 'required',
      strategies: ['token']
    },
    plugins: {
      'webmaker-ratelimit': {
        enable: true
      }
    }
  }
});
```

the default ttl (15 minutes), limit (15) and generateKeyFunc ( looks up ip) can be overridden:
```
server.route({
  path: '/footwo',
  method: 'post',
  handler: handlerFunc,
  config: {
    auth: {
      mode: 'required',
      strategies: ['token']
    },
    plugins: {
      'webmaker-ratelimit': {
        enable: true,
        ttl:1000 * 60 * 60,
        limit: 100,
        generateKeyFunc: function(request) {
          return request.path + request.auth.credentials.id;
        }
      }
    }
  }
});
```

### CODE REVIEW

**Comment by cadecairos** [comment]
I've moved the rate limit code into its own repo - cadecairos/hapi-limiter (which includes a full suite of tests and 100% coverage) and added that as a dependency here.

**Comment by ashleygwilliams** [comment]
why did you close this?

**Comment by cadecairos** [comment]
Is your plan to open PRs against my branch, or open a new PR?

**Comment by ashleygwilliams** [comment]
oh i was gonna commit on your branch, but i can start a new one if you want, np. i was just confused.

**Comment by cadecairos** [comment]
I probably should've asked what your plan was, I assumed we'd continue this on a new PR

**Pull request closed without merging**
