### PR TITLE
Extract hashtags out of project descriptions and store them in an ind…

### PR DESCRIPTION
**Pull request by cadecairos**
…exed JSONB array

mozilla/webmaker-core#727

@jbuck got time to review this?

### CODE REVIEW

**Comment by cadecairos** [comment]
ping @jbuck

**Comment by xmatthewx** [comment]
@simonwex - we could use a pair of eyes on this PR to unblock our final 2015 release. I think @jbuck is tied up with EOY things.

**Comment by xmatthewx** [comment]
@simonwex - can you connect with @cadecairos to figure out if you or another engineer can help with this review? This will block our final 2015 release.

**Comment by jbuck** [comment]
This seems reasonable. r+!

**Comment by xmatthewx** [comment]
yay :clap: thanks team

**Comment by cadecairos** [comment]
Caught some last minute issues, fixed em up and also rebased.

**Comment by cadecairos** [comment]
migration run on staging, merging to develop!

**Pull request merged**
